myapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => redirect('/noticia')

  #post '/news/' => 'noticia#index'
  resources :noticia do
    resources :comments
  end
  resources :users
  namespace :api, defaults: { format: "json" } do
    resources :noticia, only: [:index, :create, :show, :update, :destroy]

  end
  # NEWS
  get 'api/news/' => 'api/noticia#index'
  post 'api/news/' => 'api/noticia#create'
  get 'api/news/:id' => 'api/noticia#show'
  delete 'api/news/:id' => 'api/noticia#destroy'
  # comments
  get 'api/news/:id/comments' => 'api/noticia#index_comments'
  post 'api/news/:id/comments' => 'api/noticia#create_comments'
  delete 'api/news/:id/comments/:id2' => 'api/noticia#destroy_comment'
  get 'api/news/:id/comments/:id2' => 'api/noticia#show_comment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

myapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :noticium
  validates :name, presence: true
  validates :body, presence: true
end

myapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @noticium = Noticium.find(params[:noticium_id])
    @comment = @noticium.comments.create(params[:comment].permit(:name, :body))
    redirect_to noticium_path(@noticium)
  end

  def destroy
      @noticium = Noticium.find(params[:noticium_id])
      @comment = @noticium.comments.find(params[:id])
      @comment.destroy

      redirect_to noticium_path(@noticium)
  end

end

myapp/app/helpers/comments_helper.rb
module CommentsHelper
end

myapp/app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <% if comment != nil %>
    <div class="thumbnail">
        <h3><%= comment.name %></h3>
        <p> <%= comment.body %> </p>
        <p> <%= link_to 'Eliminar',
        [comment.noticium, comment], method: :delete, class: "btn btn-primary", role: "button", data: {confirm: 'Estás seguro de querer continuar?'}
        %></p>
        <% if false %>
          <% if user_signed_in? %>

              <p> <%= link_to 'Eliminar',
              [comment.noticium, comment], method: :delete, class: "btn btn-primary", role: "button", data: {confirm: 'Estás seguro de querer continuar?'}
              %></p>
          <% end %>
        <% end %>
    </div>

  <% end %>
  </div>
</div>

myapp/app/views/comments/_form.html.erb
<%= form_for([@noticium, @noticium.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

myapp/app/views/comments/edit.html.erb
<h1>Editar Comentario</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>